apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-google
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-google
    spec:
      containers:
      - name: ping-google
        image: quay.io/dferoli/ping-google:0.1.1
  selector:
    matchLabels:
      app: ping-google